### ISSUE TITLE
Minimum version for nbconvert

### ISSUE THREAD

**Issue by thatlittleboy** [JanPalasek/pretty-jupyter#20]
Hi Jan,

It seems that your package depends on the new templating features of `nbconvert` introduced in `nbconvert 6.0`: described [here](https://nbconvert.readthedocs.io/en/latest/changelog.html#id23)

And it's not compatible with nbconvert 5.0 right? If so, I suggest adding in a minimum version to your package requirements.

**Comment by JanPalasek** [comment]
Hi,

Thank you for reporting.

I'll test it and fix it asap (probably in the evening CEST). If you have some trouble, please specify the necessary version in the requirement file, it should work.

I tried to have the necessary versions as loose as possible in order not to cause some compatibility problems. [requirements.txt](https://github.com/JanPalasek/pretty-jupyter/blob/main/requirements.txt) specifies versions for which it works 100 %.

**Comment by JanPalasek** [comment]
@thatlittleboy It should be working now, it's been added to the new release also. Thanks for help. It's very much appreciated.
