### ISSUE TITLE
any plan of adding 'plotly' support?

### ISSUE THREAD

**Issue by fyenne** [JanPalasek/pretty-jupyter#31]
Hi,

awesome work, thank you for sharing this.
I wonder if you are planning to add interactive plot packages support? like R markdown knitted file. it supports plotly, highcharter and many interactive plotting packages. 

thank you

**Comment by JanPalasek** [comment]
Hello,

Thank you, I'm glad you like it. I believe that plotly is already supported.

I'm one hundred percent sure that `plotly.offline.plot` works. You can create html using this function and then just print it, for example using Jinja Markdown like this: `{{ plotly.offline.plot(fig, include_plotlyjs=False, output_type='div') }}`.

I'll check out other methods too and add it to the examples. However, generally, it is possible.

**Comment by JanPalasek** [comment]
It seems to be a bit deeper issue than I previously suspected. I will add support it for the following:
- [ ] Plotly graph needs to be viewable in Jupyter. Ideally for both Jinja Markdown and normal code cells.
- [ ] Plotly graph needs to be working after export to HTML. It must be available without internet load.

**Comment by JanPalasek** [comment]
Plotly can be used in Jinja Markdown (Markdown with Python variables) this way:

Cell 1:
```python
import plotly.express as px
fig = px.bar(x=["a", "b", "c"], y=[1, 3, 2])
```
Cell 2:
```python
%%jmd
Texts

{{ fig.to_html(include_plotlyjs=False) }}

With plot between them
```

This way ensures interactivity after export using Pretty Jupyter. Also the outputted plot is shown in the JupyterLab as well.

Other environments, such as Jupyter Notebook or Visual Studio Code, have a problem with displaying plotly graphs this way. They just aren't rendering the outputted HTML. Hence on those platforms (vscode, jupyter notebook, NOT jupyterlab) if you combine markdown and Python variables, you won't see the outputted plot in the IDE, just in the exported notebook. To display the plot, this works in all environments: `fig.show(renderer="browser")` (`fig.show(renderer="iframe")` can also be considered).

So for Pretty Jupyter the best way is to create html and render that. This works works best in JupyterLab. In other environments, you can still use it. It won't be visible in the IDE, but you can view the plot e.g. with `fig.show(renderer="browser")`.

**Comment by fyenne** [comment]
Cool! I will try. Thank you!

**Comment by JanPalasek** [comment]
@fyenne I improve the support in a new version 1.2.4. Now dynamic graphs are supported as well as they are in default nbconvert. I tested it for plotly and highchart both (python-highchart package). I added example with plotly to the example here: https://github.com/JanPalasek/pretty-jupyter-examples/tree/main/main-features-demo .

You can use also `fig.show()` (without any parameter) and it will be shown in any IDE (jupyter, jupyterlab, vs code) and it will be also shown in the exported html by pretty-jupyter.

**Comment by fyenne** [comment]
thank you~
