### ISSUE TITLE
Investigate blank space at the end

### ISSUE THREAD

**Issue by JanPalasek** [JanPalasek/pretty-jupyter#68]
> I am not sure if you call it an issue, but I think the generated html would look better without the blank space at the end.
  Thank you again for your time and your package,
  Best wishes

   _Originally posted by @chengfeng-liu in https://github.com/JanPalasek/pretty-jupyter/issues/67#issuecomment-1624884051_

**Comment by chengfeng-liu** [comment]
Thank you for your patience

**Comment by JanPalasek** [comment]
@chengfeng-liu That's no problem. I'm glad you like the package.

**Comment by JanPalasek** [comment]
I added new notebook-level metadata `output.html.toc_extend_page`. If you set false to that value, it will remove the blank space at the end. The default is true.

Currently it is in master and it will be deployed in a new release.

**Comment by chengfeng-liu** [comment]
Thank you, Jan, can't wait to try it.
