### ISSUE TITLE
pretty-jupyter compatible with SoS notebooks?

### ISSUE THREAD

**Issue by Sa8th** [JanPalasek/pretty-jupyter#73]
hello, i'm using sos notebooks in jupyter lab and it seems that %load_ext pretty_jupyter doesn't work in an sos kernel. Am I doing something wrong?

**Comment by JanPalasek** [comment]
Hello. Unfortunately I dont have experience with sos notebooks. However it should be working with jupyterlab without any issues.

Is pretty jupyter installed into the python kernel in the notebook? To be sure, you can run something like this in a python code cell:

```python
!pip install pretty-jupyter
```

After this it should work with no issues.

**Comment by JanPalasek** [comment]
I'm closing the issue. I hope the solution worked. If the problem persists, feel free to reopen it.
