### ISSUE TITLE
pinned nbconvert 6 dependency

### ISSUE THREAD

**Issue by jans-code** [JanPalasek/pretty-jupyter#77]
First of all:
Thanks for this awesome template! Kudos!

My issue/question:
Is there any reason why pretty-jupyter has nbconvert pinned to <7 versions.
I have been using the template a lot with recent nbconvert v7 releases and so far it just worked splendid.

As a sidenote:
I created [this](https://github.com/jans-code/pretty_jupyter_metadata_form) metadata form extension for setting metadata for pretty-jupyter.

**Comment by JanPalasek** [comment]
Hello. The reason is these issues: https://github.com/jupyter/nbconvert/issues/1848 https://github.com/jupyter/nbconvert/issues/2019 https://github.com/jupyter/nbconvert/issues/2020
